theme: jekyll-theme-cayman
title: My GitHub Page
description: Welcome to my personal website!

# Introduction
introduction:
  name: Your Name
  summary: <YOUR INTRODUCTION>
  career: <YOUR CAREER SUMMARY>

# Skills
skills:
  - name: Programming Languages
    items:
      - Java
      - Python
      - JavaScript
  - name: Tools and Frameworks
    items:
      - Git
      - Django
      - React
  # Add more skills as needed

# Education
education:
  - degree: Bachelor of Science
    major: Computer Science
    university: Your University
    accomplishments: <YOUR EDUCATIONAL ACCOMPLISHMENTS>
    courses:
      - Course 1
      - Course 2
      - Course 3
  # Add more education entries as needed

# Achievements and Certifications
achievements:
  - name: Certification 1
    organization: Certification Organization
    date: Certification Date
    description: <DESCRIPTION OF CERTIFICATION>
  # Add more achievements and certifications as needed

# Contact
contact:
  email: your.email@example.com
  github: your-github-username
  # Add more contact information as needed
