name: GitHub Pages  # name of workflow

on:
  push:  # workflow is executed when push event occur
    branches:
      - main  # branch that will receive push event is main branch.

jobs:  # works in workflow are as follow
  build:  # work name is build
    runs-on: ubuntu-latest  # work executed in the latest version of Ubuntu

    steps:  # step by step action of work
      - name: Checkout repository  # Checkout repository step
        uses: actions/checkout@v2  # use actions/checkout and checkout current repository, that is to make copy of repository for use and modification

      - name: Set up Node.js  # Set up Node.js step
        uses: actions/setup-node@v3  # use actions/setup-node and set Node.js
        with:
          node-version: '14'  # Node.js version is 14

      - name: Install dependencies  # Install dependencies step
        run: npm install  # use npm to install dependencies. Dependency lists are in package.json file
